#!/bin/bash
#file information demo script to demonstrate position parameters
set -x
PROGNAME="$(basename "$0")"
set +x

if [[ -e "$1" ]];
then echo -e "\nFile Type:"; file "$1"; echo -e "\nFile Status:"; stat "$1"
else echo "$PROGNAME: usage: $PROGNAME file" >&2; exit
fi

