#!/bin/bash
#group position parameters $* and $@ demonstration script

print_params () {
	echo "
		\$1 = $1
		\$2 = $2
		\$3 = $3
		\$4 = $4
	"
}

pass_params () {
	echo -e "/n" '$* :'; print_params $*
	echo -e "/n" '"$*" :'; print_params "$*"
	echo -e "/n" '$@ :'; print_params $@
	echo -e "/n" '"$@" :'; print_params "$@"
}

pass_params "word" "words with spaces"
