#!/bin/bash -x
#system information script with menu

delay=3 #time delay in seconds
while true; do
	clear
	cat <<- _EOF_
		Please Select:
		1. Display System Information
		2. Display Disk Space
		3. Display Home Space Utilization
		0. Quit
		_EOF_
	read -p "Please, select a menu item ->"
	
	if [[ "$REPLY" =~ ^[0-3]$ ]]; then
		if [[ "$REPLY" == 0 ]]; then 
			break 
		fi
		if [[ "$REPLY" == 1 ]]; then 
			echo "Hostname: $HOSTNAME"
			uptime
			sleep "$delay"
			continue
		fi
		if [[ "$REPLY" == 2 ]]; then 
			df -h 
			sleep "$delay" 
			continue
		fi
		if [[ "$REPLY" == 3 ]]; then
			if [[ "$(id -u)" -eq 0 ]]; then 
				echo "Home Space Utilization (All Users)"
				du -sh /home/*
				sleep "$delay"
				continue	
			else 
				echo "Home Space Utilization ($USER)"
				du -sh "$HOME"
				sleep "$delay"
				continue
			fi
		fi
	else echo "Invalid entry. Try again."; sleep "$delay"
	fi
done
echo "Programm terminated. Bye-bye"
